config/routes.rb
Rails.application.routes.draw do
  root controller: :notes, action: :index
  resources :notes, only: [:new, :create, :index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
    validates :title, presence: true
    validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = Note.all
  end

  def show
    @note = Note.find(params[:id])
  end

  def new
    @note = Note.new
  end

  def create
    @note = Note.new(params[:note])
 
    @note.save
    redirect_to @note
  end

  private
  def note_params
    params.require(:note).permit(:title, :text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dfm2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/index.html.erb
<h1>New Note</h1>

<%= link_to 'New Note', new_note_path %>

<p>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>

  <tr>
    <% @notes.each do |note| %>
    <p><%= note.title %></p>
    <p><%= note.content %></p>
    <td><%= link_to 'Show', note_path(note) %></td>
  </tr>
  <% end %>
</table>

app/views/notes/new.html.erb
<h1>Create Note </h1>

<%= form_with scope: :note, url: notes_path, local: true do |form| %>
  <p>
    <%= form.label :title %>
    <%= form.text_field :title, placeholder: 'Title' %>
  </p>
  <p>
    <%= form.label :content %>
    <%= form.text_field :content, placeholder: 'Content' %>
  </p>
  <p>
    <%= form.submit value: "Create Note" %>
  </p>
<% end %>

app/views/notes/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @note.text %>
</p>

<%= link_to 'Back', notes_path %>